- hosts: jboss_bxms_eap_centos_hosts
  remote_user: "{{ ansible_centos_user }}"
  sudo: true
  gather_facts: true

  vars:
    transfer_method: copy-from-controller
    jboss_bxms_create_default_eap_user: true

  roles:
  - jboss_common
  - jboss_eap
  - jboss_bxms
